import BtnBackToTop from "@/components/btn-back-to-top";
import Footer from "@/components/footer";
import Header from "@/components/header";
import clsx from "clsx";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";

const robotoSlab = Roboto({
  subsets: ["vietnamese", "latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(robotoSlab.className, "text-gray-700")}>
        {children}
        <BtnBackToTop />
      </body>
    </html>
  );
}
